import Woman from "../assets/images/woman.png"
import Doctor from "../assets/images/doctor.png"
import Location from "../assets/images/location.png"
import Back from "../assets/images/back.png"
import Tailor from "../assets/images/tailor.png"
import Pharma from "../assets/images/pharam.png"
import Forgot from "../assets/images/forgot.png"
import Done from "../assets/images/done.png"
import Profile from "../assets/images/profile.png"
import Logout from "../assets/images/logout.png"
import HospitalIcon from "../assets/images/Hospital.png"
import DoctorIcon from "../assets/images/doctorLog.png"
export {Woman,Doctor,Location,Back,Tailor,Pharma,Forgot,Done,Profile,Logout,HospitalIcon,DoctorIcon}
